use db;
drop TABLE if exists users;
CREATE TABLE USERS(
    USER_ID INT AUTO_INCREMENT ,
    ID VARCHAR(32) UNIQUE ,
    FIRST_NAME VARCHAR(32),
    LAST_NAME VARCHAR(32),
    ADDRESS VARCHAR(100),
    TYPE VARCHAR(32),
    PASSWORD VARCHAR(32),
    PRIMARY KEY (USER_ID)

);

DROP TABLE IF EXISTS HEALTH_CARE;
CREATE TABLE HEALTH_CARE(
    HC_ID INT AUTO_INCREMENT,
    HOSPITAL VARCHAR(32),
    DATE DATE,
    DESCRIPTION VARCHAR(100),
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    PRIMARY KEY (HC_ID)
);

DROP TABLE IF EXISTS BANK_ACCOUNTS;
CREATE TABLE BANK_ACCOUNTS(
    ACC_ID INT AUTO_INCREMENT,
    ACCOUNT_NUMBER VARCHAR(32),
    EXPIRATION_DATE DATE,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    PRIMARY KEY (ACC_ID)
);

DROP TABLE IF EXISTS TRANSACTIONS;
CREATE TABLE TRANSACTIONS(
    TRANS_ID INT AUTO_INCREMENT,
    FROM_ACCOUNT_ID INT,
    TO_ACCOUNT_ID INT,
    AMOUNT INT,
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES BANK_ACCOUNTS(ACC_ID),
    PRIMARY KEY (TRANS_ID)
);

DROP TABLE IF EXISTS CONVICTIONS;
CREATE TABLE CONVICTIONS(
    CONVICTION_ID INT AUTO_INCREMENT PRIMARY KEY ,
    USER_ID INT,
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

DROP TABLE IF EXISTS DEPORTS;
CREATE TABLE DEPORTS (
    DEPORT_ID INT AUTO_INCREMENT PRIMARY KEY ,
    MIGRATION_ID INT,
    DESCRIPTION VARCHAR(32),
    FOREIGN KEY (MIGRATION_ID) REFERENCES MIGRATIONS(MIGRATION_ID)
);

DROP TABLE IF EXISTS MIGRATIONS;
CREATE TABLE MIGRATIONS(
    MIGRATION_ID INT AUTO_INCREMENT,
    FROM_COUNTRY VARCHAR(32),
    TO_COUNTRY VARCHAR(32),
    DATE DATE,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    PRIMARY KEY (MIGRATION_ID)
);